# Generated by Django 4.1.3 on 2022-11-04 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Jméno')),
                ('surname', models.CharField(max_length=200, verbose_name='Příjmení')),
                ('street_address', models.CharField(max_length=200, verbose_name='Ulice a číslo popisné')),
                ('city', models.CharField(max_length=100, verbose_name='Město')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Poštovní směrovací číslo')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('MAJETEK', 'Pojištění majetku'), ('HAVARIJNI', 'Havarijní pojištění'), ('ZIVOTNI', 'Životní pojištění'), ('URAZOVE', 'Úrazové pojištění'), ('ODPOVEDNOSTI', 'Pojištění odpovědnosti')], max_length=30, verbose_name='Typ pojištění')),
                ('subject', models.CharField(max_length=100, verbose_name='Předmět pojištění')),
                ('amount', models.PositiveIntegerField(verbose_name='Pojistná částka')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Pojištění od')),
                ('date_to', models.DateField(default=datetime.date.today, verbose_name='Pojištění do')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
